### ISSUE TITLE
Consider describing RTP/RTCP muxing thing

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-use-it-or-lose-it#11]
Reclamation of code points here was eventually successful.  Might talk to some mmusic folks about the history there.

**Comment by martinthomson** [comment]
SDP also provides great examples of ossified fields.  Consider the RTP/AVP RTP/SAVP RTP/AVPF RTP/SAVPF mess.

**Comment by tfpauly** [comment]
EDM discussion: OK to close this one

**Comment by martinthomson** [comment]
"SDP is great example of ossification onto a really terrible design."
