### ISSUE TITLE
Jari's comments

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-use-it-or-lose-it#17]
@jariarkko says

> The areas of concern I personally have are s3.2 and s4.4 and possibly better discussion of where this advice and experience applies and where it does not. Machines vs. Humans, applications vs. network gear, etc.

Right now, I don't know how to act based on this.  This will need more discussion.

**Comment by jariarkko** [comment]
I left a comment in IAB-email about some suggestions on what to do.

**Comment by martinthomson** [comment]
A reponse was given there, including several changes.  Closing in favour of more specific issues.
