### ISSUE TITLE
examples of invariants helping?

### ISSUE THREAD

**Issue by kaduk** [intarchboard/draft-use-it-or-lose-it#26]
On the face of it, explicitly saying "these are the invariants" ought to imply that everything not listed is subject to change.  Have we been specifying invariants anywhere for long enough to know whether this naive expectation actually holds?

**Comment by martinthomson** [comment]
Welcome to the experiment.  I'm not aware of any attempts at the level we're attempting in QUIC (and I guess TLS to a lesser degree).  I've seen other protocols with less distinct versions of this text, but it's hard to know to what extent that has been successful as it is less obvious.

**Comment by tfpauly** [comment]
We do have older examples, as being cited #63
