### ISSUE TITLE
Discuss greasing as an addition to an existing protocol, versus being part of it from the start

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-use-it-or-lose-it#32]
We may want to consider the distinction between trying to add greasing to an existing protocol (TLS, HTTP) versus adding it from the start (QUIC).

**Comment by DavidSchinazi** [comment]
The doc doesn't distinguish between adding GREASE at the start (e.g. QUIC) vs retrofitting it (e.g. TLS). Perhaps we should mention that it is useful in both cases. An important property here is that we need the joint to get exercised periodically: adding a new extension every so often works, and GREASE allows us to artificially increasing the cadence in cases where it isn't exercised. It's also possible to force this cadence by coordinating and evolving protocols periodically (e.g. minting a new QUIC version number every 6 months that is the same as QUICv1).

**Comment by martinthomson** [comment]
See #42.  It doesn't do all of the above, but it might help.
