### ISSUE TITLE
Provide an example for cases where an extension mechanism is mandatory but not used

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-use-it-or-lose-it#34]
Can we provide an example for this text?

Caution is advised to avoid assuming that building a dependency on an extension
mechanism is sufficient to ensure availability of that mechanism in the long
term.  If the set of possible uses is narrowly constrained and deployments do
not change over time, implementations might not see new variations or assume a
narrower interpretation of what is possible.  Those implementations might still
exhibit errors when presented with new variations.

**Comment by martinthomson** [comment]
Stephen had a good example of the must-understand extensions in X.509 that might work.

**Comment by tfpauly** [comment]
TLS signature algorithms were a finite enough set that didn't have changes that made extending it very difficult, as one example.

We can also back-reference to the "examples of disuse" section here.

**Comment by tfpauly** [comment]
Pointing to the TLS version problem as an example of where implementations required a narrow set would be good.

**Comment by martinthomson** [comment]
We have the IP version stuff already.  Would that be a better example?

**Comment by fluffy** [comment]
SIP messages start with "SIP/2.0" - Good Luck with changing that 2.0 to anything else and having anything useful happen

**Comment by tfpauly** [comment]
We've moved most examples to the appendix, closing this.
