### ISSUE TITLE
Can we provide guidelines for frequency of active use?

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-use-it-or-lose-it#36]
The section on Active Use currently says:

There are currently no firm
guidelines for new protocol development.

Can we do a bit better here to define some principles about how deployment timings and evolution should relate to the use of extension points? Or does that become a separate document?

**Comment by martinthomson** [comment]
Might be worth leaving out of scope.

**Comment by tfpauly** [comment]
The solution is out of scope, but we can look at rewording to say "more experimentation needs to be done", or that it would be useful to figure out the cadence that is required for active use of a given protocol to help it not ossify.

**Comment by martinthomson** [comment]
Tommy, if you can suggest a different sentence, that would be good.

**Comment by fluffy** [comment]
I think we should remove  "There are currently no firm guidelines for new protocol
   development."  A document like this is never going to be able to give hard guidelines on this or any of the other section which are equally vague on how to achieve the goals. The goals are clearly stated here - no need to do more.

**Comment by tfpauly** [comment]
Yeah, I'll just remove the sentence.
