### ISSUE TITLE
Threat model

### ISSUE THREAD

**Issue by chris-wood** [intarchboard/draft-use-it-or-lose-it#39]
There's a lot of great material in this document, but I think one thing that's missing is the threat model. I think this was discussed on a prior call, but consider the following two types of TLS examples:

1. PQ key shares in an extension: in practice, we're primarily concerned with whether or not larger flights will make it through the network. The adversary is not an active attacker, but a benign, possibly buggy middlebox. Greasing to exercise size limits on TLS flights seems like a way to test this in practice.
2. ECH: in practice, we're primarily concerned with whether passive or active middleboxes will tamper with or otherwise block connections using this extension. Greasing _might_ also apply here, but it's less clear than the above example.

In general, the threat model here seems to be more in line with (1). The syntax (wire image) of a protocol might trigger certain middlebox or endpoint behavior that is undesired, and so greasing to avoid these seems generally good. In contrast, (2) modifies both the syntax _and_, in way, the semantics of the protocol. Greasing in the spirit of this draft doesn't seem immediately applicable. 

If it would be useful, I can try and contribute some text to clarify the desired threat model.

**Comment by martinthomson** [comment]
Useful: yes; easy: no.

To start with, I think that the ECH greasing is not entirely in scope here.  Part of that is related to the threat model, where we are considering adversaries of varying levels of sophistication and motivation who might want to block, disrupt, or undermine ECH deployment.  That's a little beyond the scope of this document I think.

The PQ thing is twofold: it's a performance optimization problem (handshakes that span multiple packets, exceeding congestion windows or anti-amplification limits), and a problem where implementations choke on big messages.  I suspect that the former is worse than the latter, but I have no direct information.

The main thing this draft attempts to address is the potential for neglect or laziness to stymie attempts to evolve protocols.  The goal is to capture all the natural pressures on implementations that might lead to ossifying choices.  This includes economy of implementation and various security-based things.  Aside from outright bugs, we are talking about implementations deliberately building features that constrain or prevent protocol evolution.  

So the threat model here is an actor that is either ignorant of or sufficiently insulated from the effects of ossification.  Nothing in the document - except perhaps from the encryption bit - is effective against a deliberate attempt to prevent protocol evolution.

ECH definitely has a threat model that is a superset of this on that basis.

PQ might fit if we're just talking about bugs, but it might just be running into limits of what is fair game for standardization if we are talking about the performance aspects.  If you look at QUIC, the limits of standardization are clear: we could say "all networks MUST support UDP", but that won't stop networks from choosing to block UDP.  We can change the cost-benefit analysis by making QUIC support more or less attractive, but we can't take that choice away altogether.

**Comment by fluffy** [comment]
If protocols had clear Invariants, firewalls would be more likely to enforce theses that make up their own view of things they think are invariants that are not. For example, SIP does not specify a max length for a a header field value so many firewalls make up their own limits and that impacts future use of new larger values.
