### ISSUE TITLE
Codepoint reclaim is difficult if negotiation with every node is needed

### ISSUE THREAD

**Issue by jariarkko** [intarchboard/draft-use-it-or-lose-it#41]
The current draft says:

"Codepoints that are reserved for future use can be especially problematic. Reserving codepoints without attributing semantics to their use can result in diverse or conflicting semantics being attributed without any hope of interoperability. An example of this is the "class E" address space in IPv4 {{?RFC0988}}, which was reserved without assigning any semantics. For protocols that can use negotiation to attribute semantics to codepoints, it is possible that unused codepoints can be reclaimed for active use, though this requires that the negotiation include all protocol participants."

This is valid of course. The text is good as is. However, it might be useful to point out that reclaiming in class E type cases is difficult, because you'd have to negotiate with everyone on the path, as otherwise the intervening routers may discard packets that seemingly use wrong kind of addresses. Or clarify that the latter part of the paragraph applies only to actually *unused* codepoints, whereas *reserved-but-unused* has likely lead to code that prohibits the use.

E.g., one could add this text to the end of the paragraph: "This is in practice impossible in situations such as those involving class E addresses, as all protocol participants would have to include every node along the path."

**Comment by martinthomson** [comment]
Or maybe just "...which includes every node on the path"
