### ISSUE TITLE
Consider restructuring section 4

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-use-it-or-lose-it#43]
Consider grouping as:

Active Use
- Extensions
- Version Negotiation (active use of the layer that contains you)
- Filler/grease

Other
- Crypto
- Invariants
- Feedback

**Comment by tfpauly** [comment]
Or break out feedback into it's own.. don't call this "other".

**Comment by martinthomson** [comment]
I would say instead:

* Active Use (with the content from the section lifted up into the top of the section)
  * Version Negotiation (as active use)
  * Faking Active Use
* Supplementary Defensive Techniques (it's not *literally* "Other"; but I would be happy to get better suggestions; framing would be that these - in addition to active use - might help)
  * Crypto
  * Invariants
  * Feedback

I realize that this structure has its own shortcomings, but one thing that is nice is that it doesn't require a whole lot of rewriting to get to this point.
