### ISSUE TITLE
ideas to make the document more crisp and shorter

### ISSUE THREAD

**Issue by mirjak** [intarchboard/draft-use-it-or-lose-it#53]
The message of the document is rather easy and I think it would help to convey this message more clearly if the document would be shorter (also more crisp and less redundant maybe). Here are some proposals:

1) I find the intro text in section 2 rather long and the content of 2.1. more strong to start with and then maybe cut the intro text to:

"Bugs in how new codepoints or extensions can manifest as abrupt termination of sessions, errors, crashes, or disappearances of endpoints and timeouts. These interoperability problems can hinder or stop deployment of new, valuable features even if the negative reactions happen infrequently or only under relatively rare conditions. Fixing bugs
that limit interoperability involves a difficult process that includes identifying the cause of these errors, finding the responsible implementation(s), coordinating a bug fix and release plan, contacting users and/or the operator of affected services, and waiting for the fix to be deployed. Especially for protocols involving multiple parties or that are considered critical infrastructure (e.g., IP, BGP, DNS, or TLS), it could even be necessary to come up with a new protocol design that uses a different method to achieve the same result."

2) I would move the examples in 2.2. to the appendix and maybe only keep this paragraph (of the TLS section):

"Even where extension points have multiple valid values, if the set of permitted values does not change over time, there is still a risk that new values are not tolerated by existing implementations. If the set of values for a particular field remains fixed over a long period, some implementations might not correctly handle a new value when it is introduced. For example, implementations of TLS broke when new values of the signature_algorithms extension were introduced."

3) In section 2.3 the part about MPTCP and TCP Open could also go to the appendix (and maybe provide a bit more insights there).

4) maybe 3.1 could also go to the appendix; also because the last two paragraphs in 3.1. are really redundant with the intro of section 3.

5) I know we just shuffled this around but I guess section 3.2 and 3.3 could also be subsections of 4. I'm actually not quite sure what the purpose or message of section 3 is...?

**Comment by martinthomson** [comment]
I've tried to enact some of this advice, which I think is timely.  Take a look and see what you think about the changes.  If they help, then I'll take them and we can iterate on the rest of this.  I've left some of the suggestions unimplemented, but I think that tightening things up more would be good.

**Comment by tfpauly** [comment]
Moving content to appendix helped a lot here.
