### ISSUE TITLE
Mention invariants

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-use-it-or-lose-it#6]
...and their interaction with greasing. Invariants are the properties of the protocol that you don't want to protect.

**Comment by martinthomson** [comment]
The interaction with greasing is a complementary one.  And both assume a very particular threat model.  The goal is not to defend against a motivated adversary, but to help those that aim to implement the protocol faithfully.  For greasing, there is an active mechanism that provides gentle encouragement to do the right thing; for invariants, the goal is more modest.  Invariants aim to clearly document those pieces of the protocol that are *intentionally ossified into the design*, as opposed to those things are are merely exposed to ossification.

**Comment by martinthomson** [comment]
@britram, @mirjak, do you have anything to add here?

**Comment by mirjak** [comment]
One question that I had was if we maybe should use the term greasing a bit more generic than "just" a specific technique as used by TLS. For me defining invariants, by saying these bits are fixed, also means that you need to make sure that all other bits vary (randomly) and could not be ossified accidentally. That's a bit stronger than just complementing each other, as you say above. I would even say that you need one for the other: if you define invariants, you must think about greasing/flexibility of everything else. Does that make sense?
