### ISSUE TITLE
Back claims more

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-use-it-or-lose-it#9]
From Stephen Farrell:

> There are a bunch of assertions in the draft that
may or may not be true but that are asserted as if
they are true. I would bet that a bunch of 'em are
true but don't see sufficient evidence given or cited.
To take the earliest example: "Protocols can react
to these shifts in one of three ways: adjust usage
patterns within the constraints of the protocol,
extend the protocol, and replace the protocol." Well,
first off, protocols don't react, chemicals and
living things do:-) But assuming you mean some class
of person, I at least can ignore the hell out of
many many things as another option. So this doesn't
seem to be a correct analysis of the options. I
think there are a good few examples like this and
that those add up to too many to be sure how they
may affect the overall argument.

First step: collect the instances where this class of error might appear.  Then perform some analysis.

**Comment by tfpauly** [comment]
EDM discussion: document has been re-worked and clarified, good to re-review
